version: '3'

services: 
  db:
    image: postgres:14.4
    restart: always
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    container_name: ${POSTGRES_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  anylistapp: 
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: nest-graphql
    container_name: AnylistApp
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"